version: '3.7'

services:
  fastapi_template:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fastapi_template_dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always